name: Publish to GitHub Packages and npmjs.com

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      # 1️⃣ 拉取代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ 设置 Node.js 环境
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      # 3️⃣ 安装依赖（用 Yarn）
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # 4️⃣ 构建
      - name: Build project
        run: yarn build

      # 5️⃣ 发布到 GitHub Packages
      - name: Publish to GitHub Packages
        run: npm publish --registry=https://npm.pkg.github.com/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 6️⃣ 发布到 npmjs.com
      - name: Publish to npmjs.com
        run: npm publish --registry=https://registry.npmjs.org/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
